# permissions for end users to view digicertissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: digicertissuer-viewer-role
rules:
- apiGroups:
  - certmanager.cloud.sap
  resources:
  - digicertissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certmanager.cloud.sap
  resources:
  - digicertissuers/status
  verbs:
  - get
