apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: digicert-issuer
  name: digicert-issuer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digicert-issuer
  labels:
    app.kubernetes.io/name: digicert-issuer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: digicert-issuer
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: digicert-issuer
    spec:
      containers:
      - command:
        - /digicert-issuer
        args:
        - --enable-leader-election
        image: digicert-issuer:latest
        name: digicert-issuer
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
