name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: IMG=ghcr.io/sapcc/digicert-issuer make docker-build
    - name: Push the Docker image
      run: IMG=ghcr.io/sapcc/digicert-issuer make docker-push
