name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMG: ghcr.io/sapcc/digicert-issuer
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GH_TOKEN}}
    - name: Build and publish the Docker image
      run: make docker-build docker-push
